apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tool
  template:
    metadata:
      labels:
        app: my-tool
    spec:
      containers:
        - name: my-tool
          image: hammad2005/my-tool:latest
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "alnafi"
            - name: MYSQL_HOST
              value: "my-mysql"
          volumeMounts:
            - name: config-volume
              mountPath: /tool/config/mylinux.json
              subPath: mylinux.json
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: tool-config
      restartPolicy: Always
