apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdDEyMw==        # base64 of 'root123'
  user: bXlzcWxfdXNlcg==             # base64 of 'mysql_user'
  password: dGVzdDEyMw==             # base64 of 'test123'
